language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

install:
  - export DSPOT_VERSION=`grep '<version>' dspot/pom.xml | head -n 1 | sed -e 's/<version>//' -e 's/<\\/version>//' -e 's/ *//g'`
  - export MAVEN_HOME=`mvn --version | grep 'Maven home' | sed -e 's/Maven h.* //'`

script:
  - mvn clean install
  - cd dspot && java -jar target/dspot-$DSPOT_VERSION-jar-with-dependencies.jar --example

after_success:
  - mvn clean test jacoco:report coveralls:report
  - cd .. && ./.travis/travis-deploy.sh

branch:
  only:
    - master